# Generated by Django 5.0.2 on 2025-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionparameters',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='productionparameters',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionparameters',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionparameters',
            name='speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionparameters',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionparameters',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
