# Generated by Django 5.0.2 on 2025-04-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productionparameters_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionparameters',
            name='is_target',
            field=models.BooleanField(default=False),
        ),
    ]
