# Generated by Django 5.0.2 on 2025-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.FloatField(verbose_name='Влажность')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('speed', models.FloatField(verbose_name='Скорость конвейера')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Параметр производства',
                'verbose_name_plural': 'Параметры производства',
                'ordering': ['-timestamp'],
            },
        ),
    ]
